INSERT INTO RAIL_SWITCHES (checked, checked_comment) VALUES
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null),
    (0, null);



--INSERT INTO TO_BE_CHECK_SWITCHES (id, checked, checked_comment)
--SELECT id, checked, checked_comment FROM RAIL_SWITCHES where id <= 10;

