
DROP TABLE IF EXISTS RAIL_SWITCHES;

CREATE TABLE RAIL_SWITCHES (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  checked tinyint(1) NOT NULL,
  checked_comment VARCHAR(250)
);

DROP TABLE IF EXISTS CHECKED_SWITCHES;

CREATE TABLE CHECKED_SWITCHES (
  id BIGINT NOT NULL,
  checked tinyint(1) NOT NULL,
  checked_comment VARCHAR(250),
  checked_by VARCHAR(50)
);

DROP TABLE IF EXISTS TO_BE_CHECK_SWITCHES;

CREATE TABLE TO_BE_CHECK_SWITCHES (
  id BIGINT NOT NULL,
  checked tinyint(1) NOT NULL,
  checked_comment VARCHAR(250),
  group_id tinyint(1) NOT NULL
);

